// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV6nnHkzVExfsFQfFoZdezzjkdtyrEwnM',
    appId: '1:640900799845:web:3a07db42bc4568ad8d558c',
    messagingSenderId: '640900799845',
    projectId: 'whats-chat-app-245e8',
    authDomain: 'whats-chat-app-245e8.firebaseapp.com',
    storageBucket: 'whats-chat-app-245e8.firebasestorage.app',
    measurementId: 'G-M5274YH9D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsA1MFSzJvnQ5PT2FkbLJm_jiZX56lLvc',
    appId: '1:640900799845:android:1808d5b9e318dfd98d558c',
    messagingSenderId: '640900799845',
    projectId: 'whats-chat-app-245e8',
    storageBucket: 'whats-chat-app-245e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPCV0VTs4IdmmodIFQElgTsSq17opdAE',
    appId: '1:640900799845:ios:d891f031ef583bc88d558c',
    messagingSenderId: '640900799845',
    projectId: 'whats-chat-app-245e8',
    storageBucket: 'whats-chat-app-245e8.firebasestorage.app',
    iosBundleId: 'com.example.chatMaterial3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLPCV0VTs4IdmmodIFQElgTsSq17opdAE',
    appId: '1:640900799845:ios:d891f031ef583bc88d558c',
    messagingSenderId: '640900799845',
    projectId: 'whats-chat-app-245e8',
    storageBucket: 'whats-chat-app-245e8.firebasestorage.app',
    iosBundleId: 'com.example.chatMaterial3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV6nnHkzVExfsFQfFoZdezzjkdtyrEwnM',
    appId: '1:640900799845:web:639986d8eeccad908d558c',
    messagingSenderId: '640900799845',
    projectId: 'whats-chat-app-245e8',
    authDomain: 'whats-chat-app-245e8.firebaseapp.com',
    storageBucket: 'whats-chat-app-245e8.firebasestorage.app',
    measurementId: 'G-04X2MXJ7SS',
  );
}
